//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsOrdering
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.EMPLOYEES1 = new HashSet<EMPLOYEE>();
            this.TRAINS = new HashSet<TRAIN>();
        }
    
        public int employee_id_number { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string telephone_number { get; set; }
        public System.DateTime birth_date { get; set; }
        public int position_id { get; set; }
        public int station_id { get; set; }
        public Nullable<int> employer_id_number { get; set; }
        public System.DateTime appointment_date { get; set; }
    
        public virtual POSITION POSITION { get; set; }
        public virtual STATION STATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEES1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAIN> TRAINS { get; set; }
    }
}
