//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsOrdering
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINS_WAGONS
    {
        public int train_wagon_id { get; set; }
        public int train_id { get; set; }
        public int wagon_number { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
        public virtual WAGON WAGON { get; set; }
    }
}
