//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayDBConnection : DbContext
    {
        public RailwayDBConnection()
            : base("name=RailwayDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<POSITION> POSITIONS { get; set; }
        public virtual DbSet<REPAIR> REPAIRS { get; set; }
        public virtual DbSet<STATION> STATIONS { get; set; }
        public virtual DbSet<STATIONS_CONNECTIONS> STATIONS_CONNECTIONS { get; set; }
        public virtual DbSet<TRAIN> TRAINS { get; set; }
        public virtual DbSet<TRAINS_WAGONS> TRAINS_WAGONS { get; set; }
        public virtual DbSet<WAGON> WAGONS { get; set; }
    }
}
