//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAIN()
        {
            this.TRAINS_WAGONS = new HashSet<TRAINS_WAGONS>();
        }
    
        public int train_id { get; set; }
        public int driver_id_number { get; set; }
        public int order_id { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ORDER ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINS_WAGONS> TRAINS_WAGONS { get; set; }
    }
}
